UNET:
    dataset: 'gmchallenge'
    lr: 0.001
    num_epochs: 10
    model_type: "unet"
    init_type: glorot
    activation: "ternarytanh"
    quantization: "Normal" # "INT", "BNN", "Normal", "FIXED"
    activation_f_width: 4
    activation_i_width: 4
    weight_f_width: 4
    weight_i_width: 4
    gpu_core_num: 1
    trained_model: "./export/nana/results/logs/em_001_1/em_001_1.pkl"
    experiment_name: "em_001_10_fixed_inf"
    log_output_dir: "./export/nana/results/logs/"
    operation_mode: "inference" # normal, visualize, retrain, inference
    # trained_model: ""
